project:
  type: book
  output-dir: docs

book:
  title: "Introduction to Calculus"
  author: "James Watmough"
  date: "2023-01-14"
  chapters:
    - index.qmd
    - functions.qmd
    - trigonometric_functions.qmd 
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: lecturenotes-md




