project:
  type: book
  output-dir: docs

book:
  title: "Introduction to Calculus"
  author: "James Watmough"
  date: "2023-01-14"
  chapters:
    - index.qmd
    - functions.qmd
    - trigonometric_functions.qmd 
    - continuity.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    code-fold: true
    code-summary: "Show the code"
    theme: cosmo
  pdf:
    documentclass: lecturenotes-md

execute:
  freeze: auto




